services:
  - type: web
    name: monitor-de-itens
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn run:app
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: ONESIGNAL_APP_ID
        sync: false
      - key: ONESIGNAL_API_KEY
        sync: false
      - key: FLASK_ENV
        value: production